### ISSUE TITLE
Forking your theme

### ISSUE THREAD

**Issue by terchris** [OpenGov-OpenData/ckanext-cob_theme#3]
Hi
I did some searching for good ckan themes and I think that yours is great. 
I Forked it and I'm trying to get it working. It seems that you have not published all the code.

I get error message saying home/snippets/hero_slider.html cannot be found

Checking the code. Its not there. 

I will figure it out. But it would be a lot simpler if you open sourced that part to.

Regards
Terje

**Comment by jqnatividad** [comment]
Hi @terchris.  Glad you like it.  We used Boston's digital branding guidelines the City of Boston created in collaboration with IDEO - https://www.boston.gov/departments/innovation-and-technology/brand-guidelines

When @jguo144  implemented it, we also created and open-sourced the hero slider, which you can find here https://github.com/OpenGov-OpenData/ckanext-heroslider

**Comment by terchris** [comment]
Hi
I have managed to get it working at http://urbalurba.no 

I spent quite some time. But I wrote a howto. 
My plan is to fork the project and put all doc there.
